%% Information used later
fs_setup('6.0');
subjectsPath = '/Volumes/Atlantic/research/fMRI/faceword/freesurfer/subjects';
fs_subjdir(subjectsPath);

funcPath = '/Volumes/Atlantic/research/fMRI/faceword/freesurfer/Data_fMRI';
template = 'self';
fs_funcdir(funcPath);
cd(funcPath);
% % save a new sessid file for faceword*_self
% sessSelf = fs_funcdir(funcPath, 'faceword*_self');
% fs_createfile('sessid_E2_self', sessSelf(1:21));

sessList = fs_sesslist('sessid_E2_self');
sessList = sessList(1:20);

outPath = fullfile('~', 'Desktop', 'FaceWord_checklabel_E2');
fm_mkdir(outPath);

% Setting for labels
anaList = {'loc_self.lh', 'loc_self.rh'};

%% Convert labels from fsaverage to all subjects
% ?h.MFS.label
msfLabels = {'lh.MFS.label', 'rh.MFS.label'};
fscmd_mfs = fs_label2label('fsaverage', msfLabels, fs_subjcode(sessList), 'samename');

% lh.OTS.label
fscmd_ots = fs_label2label('fsaverage', 'lh.OTS.label', fs_subjcode(sessList), 'samename');

% fscmd_mt = fs_label2label('fsaverage', 'lh.MT_exvivo.label', fs_subjcode(sessList([16])), 'lh.MT.label');

%% %%%%%%%%%%%%%%%%%%%% update labels with 'maxresp' %%%%%%%%%%%%%%%%%%%%%%

% FFA1/2
fs_drawlabel(sessList(1), anaList, 'f-vs-o', 1.3, {'ffa1', 'ffa2'}); 
% fs_drawlabel(sessList(5), anaList(1), 'f-vs-o', 1.3); 

cellfun(@(x) fs_trimlabel('roi.rh.f13.f-vs-o.ffa2.label', x, outPath, ...
    'method', 'maxresp', 'showinfo', 1, 'peakonly', 0, 'reflabel', 'lh.MFS.label'),...
    sessList, 'uni', false);

fs_drawlabel(sessList([1 2 7:9 14 17]), anaList(2), 'f-vs-o', 1.3, {'ffa12'}); 

cellfun(@(x) fs_trimlabel('roi.lh.f13.f-vs-o.ffa12.label', x, outPath, ...
    'ncluster', 3, 'reflabel', 'lh.MFS.label', 'lowerthresh', 1, ...
    'method', 'maxresp', 'showinfo', 1, 'peakonly', 0), sessList([7 14]), 'uni', false);

% VWFA
fs_drawlabel(sessList, anaList(1), 'w-vs-o', 1.3); 

cellfun(@(x) fs_trimlabel('roi.lh.f13.w-vs-o.label', x, outPath, ...
    'method', 'maxresp', 'showinfo', 1, 'peakonly', 0, 'reflabel', 'lh.OTS.label'), ...
    sessList(9), 'uni', false);

% LO
fs_drawlabel(sessList([2 3 5 8 9 11 13 17 ]), anaList(2), 'o-vs-scr', 1.3); 

fs_drawlabel(sessList([2 3 7 8 10 13 14 17 18]), anaList(1), 'o-vs-scr', 1.3, 'manual'); 
fs_drawlabel(sessList(10), anaList(1), 'o-vs-scr', 1.3); 

cellfun(@(x) fs_trimlabel('roi.rh.f13.o-vs-scr.label', x, outPath, ...
    'ncluster', 1, 'method', 'maxresp', 'showinfo', 1, 'peakonly', 0, ...
    'reflabel', 'lh.MT.thresh.label'), ...  
    sessList, 'uni', false); 

cellfun(@(x) fs_trimlabel('roi.rh.f13.o-vs-scr.label', x, outPath, ...
    'ncluster', 6, 'method', 'maxresp', 'showinfo', 1, 'peakonly', 0, ...
    'reflabel', 'lh.MT.thresh.label', 'lagnvtx', 20, 'maxiter', 100), ...  
    sessList([17]), 'uni', false);  % lh 4 11 12 13


cellfun(@(x) fs_trimlabel('roi.lh.f13.o-vs-scr.manual.label', x, outPath, ...
    'ncluster', 6, 'method', 'maxresp', 'showinfo', 1, 'peakonly', 0, ...
    'reflabel', 'lh.MT.thresh.label', 'lagnvtx', 20, 'maxiter', 100), ...  
    sessList([18]), 'uni', false);  % 2 7 10 13 14 
% 24161

%%%%%%%%%%%%% print the labels
labelList = {{'roi.lh.f-vs-o.ffa1.label','roi.lh.f-vs-o.ffa2.label','lh.MFS.label'}; 
    {'roi.rh.f-vs-o.ffa1.label','roi.rh.f-vs-o.ffa2.label','rh.MFS.label'};
    {'roi.lh.w-vs-o.label', 'lh.OTS.label'}; 
    {'roi.lh.o-vs-scr.label', 'lh.MT.thresh.label'};
    {'roi.rh.o-vs-scr.label', 'rh.MT.thresh.label'};
    {'roi.lh.f-vs-o.ffa1.label','roi.lh.f-vs-o.ffa2.label', 'roi.lh.w-vs-o.label','roi.lh.o-vs-scr.label'};
    {'roi.rh.f-vs-o.ffa1.label','roi.rh.f-vs-o.ffa2.label', 'roi.rh.o-vs-scr.label'}};

fs_cvn_print1st(sessList, anaList, labelList(6:7), outPath,...  
    'visualimg', 0, 'showinfo', 1, 'waitbar', 1, 'viewpt', -2, 'annot', 'aparc', ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2, 'cvnopts', {'overlayalpha', 0.5});

fs_cvn_print1st(sessList, anaList, labelList(6:7), outPath, ... , 
    'visualimg', 0, 'showinfo', 0, 'waitbar', 1, 'viewpt', -2,...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);

% run fs_surflabel
thelabellist = {'roi.lh.f-vs-o.ffa1.label','roi.lh.f-vs-o.ffa2.label',... 
    'roi.rh.f-vs-o.ffa1.label','roi.rh.f-vs-o.ffa2.label',...
    'roi.lh.w-vs-o.label', ...
    'roi.lh.o-vs-scr.label', ...
    'roi.rh.o-vs-scr.label'};
[surftable, fscmd] = fs_surflabel(sessList, thelabellist, anaList, 1.3, outPath);
fs_fscmd2txt('0_fscmd_surfcluster.txt', outPath, fscmd);

labelTable = fs_labelinfo(thelabellist, fs_subjcode(sessList));


cellfun(@(x) fs_cplabel('', outPath, x, 'faceword'), thelabellist, 'uni', false);

[gm] = fs_labelgm(thelabellist, fs_subjcode(sessList));

thetable = join(surftable, gm, 'LeftKeys', {'SubjCode', 'Label'}, ...
    'RightKeys', {'SubjCode', 'Label'});

writetable(thetable, fullfile(outPath, 'labelinfo_E2.xlsx'));

%%%%%% check label overlap
over_lable = {{'roi.lh.f-vs-o.ffa1.label', 'roi.lh.w-vs-o.label'};
    {'roi.lh.f-vs-o.ffa2.label', 'roi.lh.w-vs-o.label'}};
fs_labeloverlap(over_lable, fs_subjcode(sessList), outPath);

%% Copy the labels out
cellfun(@(x) fs_cplabel('', '.', x, 'facewordN*'), thelabellist);

%% Try to create VWFA labels with contrast (words vs. the rest)
% run first level analysis with contrast of words vs. rest
% make this contrast for E2
classPairsE2_loc = {'word', {'face', 'object', 'scrambled'}};
runFn = 'run_loc.txt';
condE2 = fs_par2cond(sessList, runFn, 'loc.par');
method = 1;

[anaStruct, fscmd_con] = fs_mkcontrast(anaList, classPairsE2_loc, condE2, method, 1);

% run the first level analysis for this contrast
% remove the other contrasts files from the analysis folders
fscmd_avg = fs_selxavg3('sessid_E2_self', anaList, 0, 1, 1);

% draw labels for VWFA with f13
fs_drawlabel(sessList(2:end), anaList(1), 'word-vs-face-object-scrambled', 1.3); 
% fs_drawlabel(sessList(5), anaList(1), 'f-vs-o', 1.3); 

% update labels with maxresp
cellfun(@(x) fs_trimlabel('roi.lh.f13.word-vs-face-object-scrambled.label', x, outPath, ...
    'method', 'maxresp', 'showinfo', 1, 'peakonly', 0, 'reflabel', 'lh.OTS.label'),...
    sessList, 'uni', false);

cellfun(@(x) fs_trimlabel('roi.lh.f13.word-vs-face-object-scrambled.label', x, outPath, ...
    'ncluster', 2, 'method', 'maxresp', 'showinfo', 1, 'peakonly', 0, 'reflabel', 'lh.OTS.label'),...
    sessList([9]), 'uni', false);

% print the screenshots
fs_cvn_print1st(sessList, anaList(1), {{'roi.lh.word-vs-face-object-scrambled.label', 'lh.OTS.label'}}, outPath,...  
    'visualimg', 0, 'showinfo', 1, 'waitbar', 1, 'viewpt', -2, 'annot', 'aparc', ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2, 'cvnopts', {'overlayalpha', 0.5});

fs_cvn_print1st(sessList, anaList(1), {{'roi.lh.word-vs-face-object-scrambled.label', 'lh.OTS.label'}}, outPath, ... , 
    'visualimg', 0, 'showinfo', 0, 'waitbar', 1, 'viewpt', -2,...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);

% surface label
[surftable, fscmd] = fs_surflabel(sessList, 'roi.lh.word-vs-face-object-scrambled.label', anaList, 1.3, outPath);
fs_fscmd2txt('0_fscmd_surfcluster.txt', outPath, fscmd);

[gm] = fs_labelgm('roi.lh.word-vs-face-object-scrambled.label', fs_subjcode(sessList));

thetable = join(surftable, gm, 'LeftKeys', {'SubjCode', 'Label'}, ...
    'RightKeys', {'SubjCode', 'Label'});

writetable(thetable, fullfile(outPath, 'labelinfo_E2_words_rest.xlsx'));

% comparing w-vs-o and w-vs-rest
fs_cvn_print1st(sessList, anaList(1), {{'roi.lh.word-vs-face-object-scrambled.label', 'roi.lh.w-vs-o.label', 'lh.OTS.label'}}, outPath,...  
    'visualimg', 0, 'showinfo', 1, 'waitbar', 1, 'viewpt', -2, 'annot', 'aparc', ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2, 'cvnopts', {'overlayalpha', 0.5});

% comparing w-vs-o and w-vs-rest
fs_cvn_print1st(sessList, anaList(1), {{'roi.lh.word-vs-face-object-scrambled.label', 'roi.lh.w-vs-o.label', 'lh.OTS.label'}}, outPath,...  
    'visualimg', 0, 'showinfo', 0, 'waitbar', 1, 'viewpt', -2, ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);

%%%%%%% double check some coordinates (for some "other" clusters)
% roi.lh.f13.word-vs-face-object-scrambled.check.label
fs_drawlabel(sessList([4, 17]), anaList(1), 'word-vs-face-object-scrambled', 1.3, 'check'); 

cellfun(@(x) fs_trimlabel('roi.lh.f13.word-vs-face-object-scrambled.check.label', x, outPath, ...
    'ncluster', 2, 'method', 'maxresp', 'showinfo', 1, 'peakonly', 0, 'reflabel', 'lh.OTS.label'),...
    sessList([4, 17]), 'uni', false);

fs_cvn_print1st(sessList([4, 17]), anaList(1), {{'roi.lh.word-vs-face-object-scrambled.check.label', 'roi.lh.w-vs-o.label', 'lh.OTS.label'}}, outPath,...  
    'visualimg', 0, 'showinfo', 0, 'waitbar', 1, 'viewpt', -2, ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);

[surftable, fscmd] = fs_surflabel(sessList([4, 17]), 'roi.lh.word-vs-face-object-scrambled.check.label', anaList(1), 1.3, outPath);

writetable(surftable, fullfile(outPath, 'labelinfo_E2_words_rest_check.xlsx'));

%% Manually solve issues regarding FFA1/2
% bisect the contiguous FFA1/2 [The overlap will be bisected manually.]

%%%%% facewordN08_self (rh) %%%%%%%
thisSess = sessList(8);

fs_cvn_print1st(thisSess, anaList{2}, ...
    {{'roi.rh.f-vs-o.ffa1.label', 'roi.rh.f-vs-o.ffa2.label'}}, outPath, ...
    'viewpt', 3, 'drawroi', 1);
Rmask = drawroipoly(himg,lookup);
fs_mklabel(Rmask, fs_subjcode(thisSess), 'roi.rh.f-vs-o.ffa2.bisectoverlap.label');

fs_updatelabel('roi.rh.f-vs-o.ffa1.label', 'roi.rh.f-vs-o.ffa2.bisectoverlap.label', ...
    fs_subjcode(thisSess));
fs_trimlabelcluster('roi.rh.f-vs-o.ffa1.label', fs_subjcode(thisSess));

fs_updatelabel('roi.rh.f-vs-o.ffa2.label', 'roi.rh.f-vs-o.ffa2.bisectoverlap.label', ...
    fs_subjcode(thisSess), @intersect);

fs_cvn_print1st(thisSess, anaList{2}, ...
    {{'roi.rh.f-vs-o.ffa1.label','roi.rh.f-vs-o.ffa2.label', 'rh.MFS.label' }},... 
    outPath, 'showinfo', 1, 'waitbar', 0, 'viewpt', -2, 'annot', 'aparc', ...
    'clim', [-5 5], 'subfolder', 2, 'cvnopts', {'overlayalpha', 0.5});
fs_cvn_print1st(thisSess, anaList{2}, ...
    {{'roi.rh.f-vs-o.ffa1.label', 'roi.rh.f-vs-o.ffa2.label', 'rh.MFS.label'}},...
    outPath, 'viewpt', -2, 'clim', [-5 5], 'subfolder', 2);

tst = fs_labeloverlap({{'roi.rh.f-vs-o.ffa1.label', 'roi.rh.f-vs-o.ffa2.label'}}, fs_subjcode(thisSess));
disp(tst);


%% Extra checking (the second best ROI)

% rFFA1
[labelMatCell1, clustrVtx1] = cellfun(@(x) fs_trimlabel('roi.rh.f13.f-vs-o.ffa12.label',...
    x, outPath, 'ncluster', 2, 'reflabel', 'rh.MFS.label', 'peakonly', 0, ...
    'lagnvtx', 10, 'maxiter', 100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList(6), 'uni', false); % :end

t = fs_labelinfo('roi.rh.f-vs-o.ffa1.alt.label', fs_subjcode(sessList(6)));

fs_cvn_print1st(sessList(6), anaList(2), ...
    {{'roi.rh.f-vs-o.ffa1.label', 'roi.rh.f-vs-o.ffa2.label', 'rh.MFS.label', 'roi.rh.f-vs-o.ffa1.alt.label'}},...
    outPath, 'viewpt', -2, 'visualimg', 0, ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);


% rFFA2
[labelMatCell1, clustrVtx1] = cellfun(@(x) fs_trimlabel('roi.rh.f13.f-vs-o.ffa12.label',...
    x, outPath, 'ncluster', 2, 'reflabel', 'rh.MFS.label', 'peakonly', 0, ...
    'lagnvtx', 10, 'maxiter', 100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList(14), 'uni', false); % :end

t = fs_labelinfo('roi.rh.f-vs-o.ffa2.alt.label', fs_subjcode(sessList(14)));

fs_cvn_print1st(sessList(14), anaList(2), ...
    {{'roi.rh.f-vs-o.ffa1.label', 'roi.rh.f-vs-o.ffa2.label', 'rh.MFS.label', 'roi.rh.f-vs-o.ffa2.alt.label'}},...
    outPath, 'viewpt', -2, 'visualimg', 0, ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);

%---

[labelMatCell1, clustrVtx1] = cellfun(@(x) fs_trimlabel('roi.rh.f13.f-vs-o.ffa12.label',...
    x, outPath, 'ncluster', 2, 'reflabel', 'rh.MFS.label', 'peakonly', 0, ...
    'lagnvtx', 10, 'maxiter', 100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList(17), 'uni', false); % :end

t = fs_labelinfo('roi.rh.f-vs-o.ffa2.alt.label', fs_subjcode(sessList(17)));

fs_cvn_print1st(sessList(17), anaList(2), ...
    {{'roi.rh.f-vs-o.ffa1.label', 'roi.rh.f-vs-o.ffa2.label', 'rh.MFS.label', 'roi.rh.f-vs-o.ffa2.alt.label'}},...
    outPath, 'viewpt', -2, 'visualimg', 0, ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);


% lLO
[labelMatCell1, clustrVtx1] = cellfun(@(x) fs_trimlabel('roi.lh.f13.o-vs-scr.manual.label',...
    x, outPath, 'ncluster', 3, 'reflabel', 'lh.MT.thresh.label', 'peakonly', 0, ...
    'lagnvtx', 100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList(2), 'uni', false); % :end

t = fs_labelinfo('roi.lh.o-vs-scr.alt.label', fs_subjcode(sessList(2)));

fs_cvn_print1st(sessList(2), anaList(1), ...
    {{'roi.lh.o-vs-scr.label', 'lh.MT.thresh.label', 'roi.lh.o-vs-scr.alt.label'}},...
    outPath, 'viewpt', -2, 'visualimg', 0, ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);

%---
[labelMatCell1, clustrVtx1] = cellfun(@(x) fs_trimlabel('roi.lh.f13.o-vs-scr.manual.label',...
    x, outPath, 'ncluster', 3, 'reflabel', 'lh.MT.thresh.label', 'peakonly', 0, ...
    'lagnvtx', 100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList(3), 'uni', false); % :end

t = fs_labelinfo('roi.lh.o-vs-scr.alt.label', fs_subjcode(sessList(3)));

fs_cvn_print1st(sessList(3), anaList(1), ...
    {{'roi.lh.o-vs-scr.label', 'lh.MT.thresh.label', 'roi.lh.o-vs-scr.alt.label'}},...
    outPath, 'viewpt', -2, 'visualimg', 0, ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);

%---
[labelMatCell1, clustrVtx1] = cellfun(@(x) fs_trimlabel('roi.lh.f13.o-vs-scr.label',...
    x, outPath, 'ncluster', 3, 'reflabel', 'lh.MT.thresh.label', 'peakonly', 0, ...
    'lagnvtx', 100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList(5), 'uni', false); % :end

t = fs_labelinfo('roi.lh.o-vs-scr.alt.label', fs_subjcode(sessList(5)));

fs_cvn_print1st(sessList(5), anaList(1), ...
    {{'roi.lh.o-vs-scr.label', 'lh.MT.thresh.label', 'roi.lh.o-vs-scr.alt.label'}},...
    outPath, 'viewpt', -2, 'visualimg', 0, ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);

%---
[labelMatCell1, clustrVtx1] = cellfun(@(x) fs_trimlabel('roi.lh.f13.o-vs-scr.label',...
    x, outPath, 'ncluster', 3, 'reflabel', 'lh.MT.thresh.label', 'peakonly', 0, ...
    'lagnvtx', 100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList(7), 'uni', false); % :end

t = fs_labelinfo('roi.lh.o-vs-scr.alt.label', fs_subjcode(sessList(7)));

fs_cvn_print1st(sessList(7), anaList(1), ...
    {{'roi.lh.o-vs-scr.label', 'lh.MT.thresh.label', 'roi.lh.o-vs-scr.alt.label'}},...
    outPath, 'viewpt', -2, 'visualimg', 0, ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);

%---
[labelMatCell1, clustrVtx1] = cellfun(@(x) fs_trimlabel('roi.lh.f13.o-vs-scr.manual.label',...
    x, outPath, 'ncluster', 3, 'reflabel', 'lh.MT.thresh.label', 'peakonly', 0, ...
    'lagnvtx', 100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList(10), 'uni', false); % :end

t = fs_labelinfo('roi.lh.o-vs-scr.alt.label', fs_subjcode(sessList(10)));

fs_cvn_print1st(sessList(10), anaList(1), ...
    {{'roi.lh.o-vs-scr.label', 'lh.MT.thresh.label', 'roi.lh.o-vs-scr.alt.label'}},...
    outPath, 'viewpt', -2, 'visualimg', 0, ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);

%---
[labelMatCell1, clustrVtx1] = cellfun(@(x) fs_trimlabel('roi.lh.f13.o-vs-scr.manual.label',...
    x, outPath, 'ncluster', 3, 'reflabel', 'lh.MT.thresh.label', 'peakonly', 0, ...
    'lagnvtx', 100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList(17), 'uni', false); % :end

t = fs_labelinfo('roi.lh.o-vs-scr.alt.label', fs_subjcode(sessList(17)));

fs_cvn_print1st(sessList(17), anaList(1), ...
    {{'roi.lh.o-vs-scr.label', 'lh.MT.thresh.label', 'roi.lh.o-vs-scr.alt.label'}},...
    outPath, 'viewpt', -2, 'visualimg', 0, ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);

%---
[labelMatCell1, clustrVtx1] = cellfun(@(x) fs_trimlabel('roi.lh.f13.o-vs-scr.manual.label',...
    x, outPath, 'ncluster', 3, 'reflabel', 'lh.MT.thresh.label', 'peakonly', 0, ...
    'lagnvtx', 100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList(18), 'uni', false); % :end

t = fs_labelinfo('roi.lh.o-vs-scr.alt.label', fs_subjcode(sessList(18)));

fs_cvn_print1st(sessList(18), anaList(1), ...
    {{'roi.lh.o-vs-scr.label', 'lh.MT.thresh.label', 'roi.lh.o-vs-scr.alt.label'}},...
    outPath, 'viewpt', -2, 'visualimg', 0, ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);


%---
[labelMatCell1, clustrVtx1] = cellfun(@(x) fs_trimlabel('roi.lh.f13.o-vs-scr.label',...
    x, outPath, 'ncluster', 3, 'reflabel', 'lh.MT.thresh.label', 'peakonly', 0, ...
    'lagnvtx', 10, 'maxiter',100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList(20), 'uni', false); % :end

t = fs_labelinfo('roi.lh.o-vs-scr.alt.label', fs_subjcode(sessList(20)));

fs_cvn_print1st(sessList(20), anaList(1), ...
    {{'roi.lh.o-vs-scr.label', 'lh.MT.thresh.label', 'roi.lh.o-vs-scr.alt.label'}},...
    outPath, 'viewpt', -2, 'visualimg', 0, ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);


% rLO
fs_drawlabel(sessList(11), anaList(2), 'o-vs-scr', 1.3, 'alt');
[labelMatCell1, clustrVtx1] = cellfun(@(x) fs_trimlabel('roi.rh.f13.o-vs-scr.alt.label',...
    x, outPath, 'reflabel', 'rh.MT.thresh.label', 'peakonly', 0, ...
    'lagnvtx', 100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList(11), 'uni', false); % :end

t = fs_labelinfo('roi.rh.o-vs-scr.alt.label', fs_subjcode(sessList(11)));

fs_cvn_print1st(sessList(11), anaList(2), ...
    {{'roi.rh.o-vs-scr.label', 'rh.MT.thresh.label', 'roi.rh.o-vs-scr.alt.label'}},...
    outPath, 'viewpt', -2, 'visualimg', 0, ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);

%---
[labelMatCell1, clustrVtx1] = cellfun(@(x) fs_trimlabel('roi.rh.f13.o-vs-scr.label',...
    x, outPath, 'ncluster', 4, 'reflabel', 'rh.MT.thresh.label', 'peakonly', 0, ...
    'lagnvtx', 20, 'maxiter', 100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList(5), 'uni', false); % :end

t = fs_labelinfo('roi.rh.o-vs-scr.alt.label', fs_subjcode(sessList(5)));

fs_cvn_print1st(sessList(5), anaList(2), ...
    {{'roi.rh.o-vs-scr.label', 'rh.MT.thresh.label', 'roi.rh.o-vs-scr.alt.label'}},...
    outPath, 'viewpt', -2, 'visualimg', 0, ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);

%---
[labelMatCell1, clustrVtx1] = cellfun(@(x) fs_trimlabel('roi.rh.f13.o-vs-scr.manual.label',...
    x, outPath, 'ncluster', 4, 'reflabel', 'rh.MT.thresh.label', 'peakonly', 0, ...
    'lagnvtx', 20, 'maxiter', 100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList(13), 'uni', false); % :end

t = fs_labelinfo('roi.rh.o-vs-scr.alt.label', fs_subjcode(sessList(13)));

fs_cvn_print1st(sessList(13), anaList(2), ...
    {{'roi.rh.o-vs-scr.label', 'rh.MT.thresh.label', 'roi.rh.o-vs-scr.alt.label'}},...
    outPath, 'viewpt', -2, 'visualimg', 0, ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);


%---
% fs_drawlabel(sessList(18), anaList(2), 'o-vs-scr', 1.3, 'manual');
[labelMatCell1, clustrVtx1] = cellfun(@(x) fs_trimlabel('roi.rh.f13.o-vs-scr.manual.label',...
    x, outPath, 'ncluster', 4, 'reflabel', 'rh.MT.thresh.label', 'peakonly', 0, ...
    'lagnvtx', 10, 'maxiter', 200, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList(18), 'uni', false); % :end

t = fs_labelinfo('roi.rh.o-vs-scr.alt.label', fs_subjcode(sessList(18)));

fs_cvn_print1st(sessList(18), anaList(2), ...
    {{'roi.rh.o-vs-scr.label', 'rh.MT.thresh.label', 'roi.rh.o-vs-scr.alt.label'}},...
    outPath, 'viewpt', -2, 'visualimg', 0, ...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2);


%% Print the screenshots of the "final" labels

% print
labelListCell = {{'roi.lh.f-vs-o.ffa1.label', 'roi.lh.f-vs-o.ffa2.label', 'lh.MFS.label'};
    {'roi.lh.word-vs-face-object-scrambled.label', 'lh.OTS.label'};
    {'roi.lh.o-vs-scr.label', 'lh.MT.thresh.label'};
    {'roi.rh.f-vs-o.ffa1.label', 'roi.rh.f-vs-o.ffa2.label', 'rh.MFS.label'};
    {'roi.rh.o-vs-scr.label', 'rh.MT.thresh.label'};
    {'roi.lh.f-vs-o.ffa1.label', 'roi.lh.f-vs-o.ffa2.label', 'roi.lh.word-vs-face-object-scrambled.label', 'roi.lh.o-vs-scr.label'};
    {'roi.rh.f-vs-o.ffa1.label', 'roi.rh.f-vs-o.ffa2.label', 'roi.rh.o-vs-scr.label'}
    }; 

fs_cvn_print1st(sessList, anaList, labelListCell(6:7), ...
    outPath, 'visualimg', 0, 'showinfo', 0, 'waitbar', 1, 'viewpt', -2, 'annot', '',...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2, 'roicolors', fm_colors);

fs_cvn_print1st(sessList, anaList, labelListCell(6:7), ...
    outPath, 'visualimg', 0, 'showinfo', 1, 'waitbar', 1, 'viewpt', -2, 'annot', 'aparc',...
    'thresh', 1.3i, 'clim', [-5 5], 'subfolder', 2, 'roicolors', fm_colors,...
    'showinfo', 1, 'cvnopts', {'overlayalpha', 0.5});


% output the csv file
labelList = {
    'roi.lh.f-vs-o.ffa1.label';
    'roi.lh.f-vs-o.ffa2.label';
    'roi.lh.word-vs-face-object-scrambled.label';
    'roi.lh.o-vs-scr.label';
    'roi.rh.f-vs-o.ffa1.label';
    'roi.rh.f-vs-o.ffa2.label';
    'roi.rh.o-vs-scr.label'
    };

labelInfo = fs_labelinfo(labelList, fs_subjcode(sessList), 'bycluster', 1);
writetable(labelInfo, fullfile('~', 'Desktop', 'faceword_E2_Label_HJ.csv'));


%% LOC 150, 200, 300mm^2

% lh: 100, 150, 200, 300
[labelMatCell150, clustrVtx150] = cellfun(@(x) fs_trimlabel('roi.lh.f13.o-vs-scr.label',...
    x, outPath, 'reflabel', 'roi.lh.o-vs-scr.label', 'peakonly', 0, ...
    'gmfn', 'roi.lh.o-vs-scr.gm', 'maxsize', 100, 'savesize', 1, ...
    'lagnvtx', 10, 'maxiter', 100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList([7 10]), 'uni', false); % :8, 10:13, 15, 17,18, 20

[labelMatCell150, clustrVtx150] = cellfun(@(x) fs_trimlabel('roi.lh.f13.o-vs-scr.label',...
    x, outPath, 'reflabel', 'roi.lh.o-vs-scr.label', 'peakonly', 0, ...
    'gmfn', 'roi.lh.o-vs-scr.gm', 'maxsize', 100, 'savesize', 0, ...
    'lagnvtx', 10, 'maxiter', 100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList([7 10]), 'uni', false); % 

% rh: 100, 150, 200, 300
[labelMatCell150, clustrVtx150] = cellfun(@(x) fs_trimlabel('roi.rh.f13.o-vs-scr.label',...
    x, outPath, 'reflabel', 'roi.rh.o-vs-scr.label', 'peakonly', 0, ...
    'gmfn', 'roi.rh.o-vs-scr.gm', 'maxsize', 300, 'savesize', 1, ...
    'lagnvtx', 10, 'maxiter', 100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList, 'uni', false); % :8, 10:13, 15, 17,18, 20

[labelMatCell150, clustrVtx150] = cellfun(@(x) fs_trimlabel('roi.rh.f13.o-vs-scr.label',...
    x, outPath, 'reflabel', 'roi.rh.o-vs-scr.label', 'peakonly', 0, ...
    'gmfn', 'roi.rh.o-vs-scr.gm', 'maxsize', 100, 'savesize', 0, ...
    'lagnvtx', 10, 'maxiter', 100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList([5 13 18]), 'uni', false); % 

% print LO label info
labelList_LO = {
    'roi.lh.o-vs-scr.label';
    'roi.lh.o-vs-scr.a100.label';
    'roi.lh.o-vs-scr.a150.label';
    'roi.lh.o-vs-scr.a200.label';
    'roi.lh.o-vs-scr.a300.label';
    'roi.rh.o-vs-scr.label';
    'roi.rh.o-vs-scr.a100.label';
    'roi.rh.o-vs-scr.a150.label';
    'roi.rh.o-vs-scr.a200.label';
    'roi.rh.o-vs-scr.a300.label';
    };

labelInfo_LO = fs_labelinfo(labelList_LO, fs_subjcode(sessList), 'bycluster', 1);
writetable(labelInfo_LO, fullfile('~', 'Desktop', 'faceword_E2_Label_LO_HJ.csv'));


%% double check FFA1/2, VWFA

cellfun(@(x) fs_trimlabel('roi.rh.f13.f-vs-o.ffa12.label',...
    x, outPath, 'reflabel', 'roi.rh.f-vs-o.ffa2.label', 'peakonly', 0, ...
    'gmfn', 'roi.rh.f-vs-o.ffa2.gm', 'maxsize', 100, 'savesize', 0, ...'method', 'concentric', ...
    'lagnvtx', 10, 'maxiter', 100, 'showinfo', 1, 'extraopt1st', { 'cvnopts', {'overlayalpha', 0.5'}}), ...
    sessList(6), 'uni', false); % 
over = fs_labeloverlap({{'roi.rh.f-vs-o.ffa1.label', 'roi.rh.f-vs-o.ffa2.label'}}, fs_subjcode(sessList(6)), outPath);


%% Make plots for representative ROIs in manuscript

labelList = {
    {'roi.lh.f-vs-o.ffa1.label','roi.lh.f-vs-o.ffa2.label', 'roi.lh.word-vs-face-object-scrambled.label','roi.lh.o-vs-scr.label'};
    {'roi.rh.f-vs-o.ffa1.label','roi.rh.f-vs-o.ffa2.label', 'roi.rh.o-vs-scr.label'}};


opts = {'visualimg', 0, 'viewpt', {[-40, -45, -20]}, ...
    'dispsig', 0, 'subfolder', 2, 'imgext', 'pdf', 'dispcolorbar', 0, ...
    'roiwidth', 1, 'cvnopts', {'rgbnan', 1}};
cellfun(@(x) fs_cvn_printlabel({labelList(1)}, x, 0, outPath, 1, opts), ...
    sessList([2 9 18]), 'uni', false);
opts = {'visualimg', 0, 'viewpt', {[40, -45, 20]}, ...
    'dispsig', 0, 'subfolder', 2, 'imgext', 'pdf', 'dispcolorbar', 0, ...
    'roiwidth', 1, 'roicolors', fm_colors([1, 2, 4]), 'cvnopts', {'rgbnan', 1}};
cellfun(@(x) fs_cvn_printlabel({labelList(2)}, x, 0, outPath, 1, opts), ...
    sessList([2 9 18]), 'uni', false);  %
